kind: pipeline
name: default

steps:
- name: prepare
  image: plugins/git
  commands:
  - git clone https://github.com/mesalock-linux/packages.git packages
  - git clone https://github.com/mesalock-linux/mkpkg.git mkpkg

- name: build-mkpkg
  image: mesalocklinux/build-mesalock-linux:latest
  pull: always
  commands:
  - cd mkpkg && cargo build --release

- name: build-packages
  image: mesalocklinux/build-mesalock-linux:latest
  commands:
  - ./mkpkg/target/release/mkpkg build `find packages -name "build.yml"`

- name: build-iso
  image: mesalocklinux/build-mesalock-linux:latest
  commands:
    - ./mesalockiso

- name: build-rootfs
  image: mesalocklinux/build-mesalock-linux:latest
  commands:
    - ./mesalockrootfs
